/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Deu
 */
public class VLogIn extends javax.swing.JFrame {

    /**
     * Creates new form VLogIn
     */
    VLogIn vl;
    public VLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_emai_Vlogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_password_Vlogin = new javax.swing.JPasswordField();
        b_login_Vlogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        b_signin_Vlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LogIn");
        setBackground(new java.awt.Color(88, 63, 91));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(184, 237, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setForeground(new java.awt.Color(208, 93, 93));
        jLabel1.setText("Email");
        jLabel1.setToolTipText("Enter you Email   ");

        tf_emai_Vlogin.setForeground(new java.awt.Color(208, 93, 93));
        tf_emai_Vlogin.setText("Enter you Email   ");
        tf_emai_Vlogin.setPreferredSize(new java.awt.Dimension(150, 40));
        tf_emai_Vlogin.setSelectionColor(new java.awt.Color(252, 108, 108));
        tf_emai_Vlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emai_VloginActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(208, 93, 93));
        jLabel2.setText("Password");
        jLabel2.setToolTipText("Enter your Password");

        tf_password_Vlogin.setForeground(new java.awt.Color(208, 93, 93));
        tf_password_Vlogin.setText("jPasswordField1");
        tf_password_Vlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_password_VloginActionPerformed(evt);
            }
        });

        b_login_Vlogin.setBackground(new java.awt.Color(208, 93, 93));
        b_login_Vlogin.setForeground(new java.awt.Color(255, 255, 255));
        b_login_Vlogin.setText("Login");
        b_login_Vlogin.setToolTipText("click to Login");
        b_login_Vlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_login_VloginActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 55, 86));
        jLabel3.setForeground(new java.awt.Color(208, 93, 93));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("don't have account ?");

        b_signin_Vlogin.setBackground(new java.awt.Color(208, 93, 93));
        b_signin_Vlogin.setForeground(new java.awt.Color(255, 255, 255));
        b_signin_Vlogin.setText("sign in");
        b_signin_Vlogin.setToolTipText("click to sign in");
        b_signin_Vlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_signin_VloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_emai_Vlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_password_Vlogin))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b_signin_Vlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_login_Vlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_emai_Vlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_password_Vlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(b_login_Vlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_signin_Vlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_signin_VloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_signin_VloginActionPerformed
       VSignIn vsRef= new VSignIn();
       vsRef.setVisible(true);
//       vl.setVisible(false);
   //    getContentPane().setVisible(false);
        setVisible(false);
        
    }//GEN-LAST:event_b_signin_VloginActionPerformed

    private void tf_emai_VloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emai_VloginActionPerformed
       
        VChatList chatlist =new VChatList();  
       chatlist.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tf_emai_VloginActionPerformed

    private void tf_password_VloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_password_VloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_password_VloginActionPerformed

    private void b_login_VloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_login_VloginActionPerformed
        // TODO add your handling code here:
           VChatList chatlist =new VChatList();  
       chatlist.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_b_login_VloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VLogIn vl=new VLogIn();
                vl.setVisible(true);
              //  Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
              //  vl.setSize(600,680);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_login_Vlogin;
    private javax.swing.JButton b_signin_Vlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_emai_Vlogin;
    private javax.swing.JPasswordField tf_password_Vlogin;
    // End of variables declaration//GEN-END:variables
}
