/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientMAINController;
import model.DataBase.ClientDB;

/**
 *
 * @author Deu
 */
public class VSignIn extends javax.swing.JFrame {

    /**
     * Creates new form VSignIn
     */
    ClientMAINController clientConRef;//=new ClientMAINController();
    ClientDB clientDBRef = new ClientDB();

    public VSignIn() {
        initComponents();
    }
    public VSignIn(ClientMAINController clientConRef)
    {
        this.clientConRef=clientConRef;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_firstname_vsignin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_lastname_vsignin = new javax.swing.JTextField();
        tf_email_vsignin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_password_vsignin = new javax.swing.JPasswordField();
        tf_confirmpassword_vsignin = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        cb_gender_vsignin = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tf_country_vsignin = new javax.swing.JTextField();
        b_login_vsignin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SignIn");
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(204, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 600));

        tf_firstname_vsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_firstname_vsigninActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name ");

        tf_lastname_vsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lastname_vsigninActionPerformed(evt);
            }
        });

        tf_email_vsignin.setMinimumSize(new java.awt.Dimension(600, 600));
        tf_email_vsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_email_vsigninActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        tf_password_vsignin.setText("jPasswordField1");
        tf_password_vsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_password_vsigninActionPerformed(evt);
            }
        });

        tf_confirmpassword_vsignin.setText("jPasswordField1");
        tf_confirmpassword_vsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_confirmpassword_vsigninActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("gender");

        cb_gender_vsignin.setBackground(new java.awt.Color(252, 207, 164));
        cb_gender_vsignin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cb_gender_vsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_gender_vsigninActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Country");

        tf_country_vsignin.setMinimumSize(new java.awt.Dimension(600, 600));
        tf_country_vsignin.setPreferredSize(new java.awt.Dimension(600, 600));

        b_login_vsignin.setBackground(new java.awt.Color(208, 93, 93));
        b_login_vsignin.setForeground(new java.awt.Color(255, 255, 255));
        b_login_vsignin.setText("Login");
        b_login_vsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_login_vsigninActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_login_vsignin, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_gender_vsignin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_country_vsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(tf_password_vsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_confirmpassword_vsignin))
                                .addComponent(tf_email_vsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(4, 4, 4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_lastname_vsignin, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(tf_firstname_vsignin)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_firstname_vsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_lastname_vsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_email_vsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_password_vsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_confirmpassword_vsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_gender_vsignin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_country_vsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(b_login_vsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 600);

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/tumblr_mwziytJejR1r2zvfoo1_500.gif"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 0, 590, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_login_vsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_login_vsigninActionPerformed
        //------------------filling DataBase with the objects--------------------
        String firstname = tf_firstname_vsignin.getText(),
                lastname = tf_lastname_vsignin.getText(),
                email = tf_email_vsignin.getText(),
                country = tf_country_vsignin.getText(),
                //----------need a method to get text from checkbox
                gender = "male",
                password = tf_password_vsignin.getText(),
                confirmpassword = tf_confirmpassword_vsignin.getText(),
                toconfirm = "";

        if (!firstname.equals(toconfirm) && !lastname.equals(toconfirm) && !email.equals(toconfirm) && !country.equals(toconfirm) && !gender.equals("") && !password.equals(toconfirm)) {

            clientDBRef.setFname(firstname);
            clientDBRef.setLname(lastname);
            clientDBRef.setEmail(email);
            clientDBRef.setCountry(country);
            clientDBRef.setGender(gender);
            if (password.equals(confirmpassword)) {
                clientDBRef.setPassword(password);
            } else {
                //---------post some error message----------------
                System.out.println("please re-write your password");
            }
            
            //---------sent the obj to controller-----------
            clientConRef.copyOfClientDbObj(clientDBRef);
        } else {
            //---------post some error message----------------
            System.out.println("some fields are empty, i guess..");
        }
        
        //------------------end of filling DataBase with the objects--------------------

        VChatList chatlist = new VChatList();
        chatlist.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_b_login_vsigninActionPerformed

    private void tf_lastname_vsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lastname_vsigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lastname_vsigninActionPerformed

    private void cb_gender_vsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_gender_vsigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_gender_vsigninActionPerformed

    private void tf_email_vsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_email_vsigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_email_vsigninActionPerformed

    private void tf_confirmpassword_vsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_confirmpassword_vsigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_confirmpassword_vsigninActionPerformed

    private void tf_password_vsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_password_vsigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_password_vsigninActionPerformed

    private void tf_firstname_vsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_firstname_vsigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_firstname_vsigninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                VSignIn vs = new VSignIn();
 //               vs.setVisible(true);
                //  vs.setSize(600,680);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_login_vsignin;
    private javax.swing.JComboBox<String> cb_gender_vsignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tf_confirmpassword_vsignin;
    private javax.swing.JTextField tf_country_vsignin;
    private javax.swing.JTextField tf_email_vsignin;
    private javax.swing.JTextField tf_firstname_vsignin;
    private javax.swing.JTextField tf_lastname_vsignin;
    private javax.swing.JPasswordField tf_password_vsignin;
    // End of variables declaration//GEN-END:variables
}
